{
 "title": "Seer",
 "time": { "from": "now-2y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "All : true,PlayEDH : games.guild_xid = 304276578005942272,Not PlayEDH : games.guild_xid != 304276578005942272,CompetitiveEDH : games.guild_xid = 113555415446413312,r/cEDH Discord : games.guild_xid = 1225118416298315857,Tolarian Community College : games.guild_xid = 574711449566445603,The Nitpicking Nerds Discord Server : games.guild_xid = 531209216443154443,i_hate_your_deck's server : games.guild_xid = 793590120049672242,Command the Cause - Gaming Club : games.guild_xid = 817867020837584906,Commander SpellTable (DE) : games.guild_xid = 752261529390284870,Asylum Gaming : games.guild_xid = 840959507747569715,EDH Tambayan : games.guild_xid = 750696719905456189,EDH Fight Club : games.guild_xid = 815001383979450368,Dungeons & Cardboard : games.guild_xid = 852684404328497172,Playing With Power MTG : games.guild_xid = 530219227924267008,MTG@Home : games.guild_xid = 689674672240984067,The Mages Guild | EDH Community : games.guild_xid = 806995731268632596,SpellTable : games.guild_xid = 699186736424681533,Oath of the Gaywatch : games.guild_xid = 757455940009328670,ChannelFireball : games.guild_xid = 508059359683543050,DOYOU EDH : games.guild_xid = 757933229931233280,Landfall: Commander en Español : games.guild_xid = 574726557675946000,cEDH Portuguese League : games.guild_xid = 799686008811290626"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "† Data applies to selected server.<br />\n‡ Data applies across all servers."
   }
  },
  {
   "title": "Games (All Time) †",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(1)\nFROM games\nWHERE started_at IS NOT NULL\n    AND $server;"
    }
   ]
  },
  {
   "title": "Players (All Time) †",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT(plays.user_xid))\nFROM games\nJOIN plays ON plays.game_id = games.id\nWHERE started_at IS NOT NULL\n    AND $server;"
    }
   ]
  },
  {
   "title": "Servers (All Time) ‡",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "rawSql": "SELECT COUNT(1) FROM guilds;" }
   ]
  },
  {
   "title": "Daily Players †",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n    $__timeGroupAlias(games.started_at,1d),\n    COUNT(DISTINCT(plays.user_xid)) AS \"players\"\nFROM games\nJOIN plays ON plays.game_id = games.id\nWHERE games.started_at IS NOT NULL\n    AND $server\n    AND  $__timeFilter(games.started_at)\nGROUP BY 1\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Games (Timespan) †",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(1)\nFROM games\nWHERE started_at IS NOT NULL\n    AND $server\n    AND $__timeFilter(started_at);"
    }
   ]
  },
  {
   "title": "Players (Timespan) †",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT(plays.user_xid))\nFROM games\nJOIN plays ON plays.game_id = games.id\nWHERE started_at IS NOT NULL\n    AND $server\n    AND $__timeFilter(games.started_at);"
    }
   ]
  },
  {
   "title": "Servers (Timespan) ‡",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(1)\nFROM guilds\nWHERE $__timeFilter(updated_at);"
    }
   ]
  },
  {
   "title": "Daily Active Users ‡",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 1, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(updated_at,1d),\n  COUNT(xid) AS \"count\"\nFROM users\nWHERE $__timeFilter(updated_at)\nGROUP BY 1\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Weekly Active Users ‡",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(updated_at,7d),\n  COUNT(xid) AS \"count\"\nFROM users\nWHERE $__timeFilter(updated_at)\nGROUP BY 1\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Monthly Active Users ‡",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(updated_at,30d),\n  COUNT(xid) AS \"count\"\nFROM users\nWHERE $__timeFilter(updated_at)\nGROUP BY 1\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Daily Games (Started vs Expired) †",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1d),\n  COUNT(id) AS \"started\"\nFROM games\nWHERE $__timeFilter(created_at)\n  AND started_at is not null\n  AND $server\nGROUP BY 1\nORDER BY 1;"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1d),\n  COUNT(id) AS \"expired\"\nFROM games\nWHERE $__timeFilter(created_at)\n  AND deleted_at is not null\n  AND $server\nGROUP BY 1\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Daily New Users ‡",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 1, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1d),\n  COUNT(xid) AS \"count\"\nFROM users\nWHERE $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "DAU:MAU ‡",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT (\n        SELECT AVG(DAU.count)\n        FROM (\n                SELECT COUNT(xid) AS \"count\"\n                FROM users\n                WHERE $__timeFilter(updated_at)\n                GROUP BY FLOOR(EXTRACT(EPOCH FROM updated_at)/86400)*86400\n                ORDER BY FLOOR(EXTRACT(EPOCH FROM updated_at)/86400)*86400\n        ) DAU\n    ) / (\n        SELECT AVG(MAU.count)\n        FROM (\n                SELECT COUNT(xid) AS \"count\"\n                FROM users\n                WHERE $__timeFilter(updated_at)\n                GROUP BY FLOOR(EXTRACT(EPOCH FROM updated_at)/2.592e+06)*2.592e+06\n                ORDER BY FLOOR(EXTRACT(EPOCH FROM updated_at)/2.592e+06)*2.592e+06\n        ) MAU\n    ) * 100.0;"
    }
   ]
  },
  {
   "title": "Weekly Server Popularity ‡",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  guilds.name AS \"server\",\n  $__timeGroupAlias(games.created_at,7d),\n  count(games.id) AS \"Games played on\"\nFROM games\nJOIN guilds ON guilds.xid = games.guild_xid\nWHERE\n  $__timeFilter(games.created_at) AND\n  guilds.name IS NOT NULL AND\n  games.started_at IS NOT NULL\nGROUP BY 1, 2\nHAVING count(games.id) > 10\n-- ORDER BY 1, 2\nORDER BY 2 ASC"
    }
   ]
  },
  {
   "title": "Daily Games (casual vs cEDH) †",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1d),\n  COUNT(id) AS \"casual\"\nFROM games\nWHERE $__timeFilter(created_at)\n  AND started_at is not null\n  AND games.guild_xid in(\n    304276578005942272, -- PlayEDH\n    574711449566445603, -- TCC\n    531209216443154443, -- Nitpicking Nerds\n    815001383979450368, -- EDH Fight Club\n    793590120049672242, -- IHYD\n    750696719905456189, -- Tambayan\n    752261529390284870, -- DE\n    840959507747569715, -- Combat Step\n    817867020837584906, -- CTC\n    757455940009328670, -- Gaywatch\n    1229388601113051198, -- Fight Club Royal\n    924643928844673045, -- Turbo\n    1176073262078378004, -- Breakfast Club\n    689674672240984067 -- MTG@Home\n  )\nGROUP BY 1\nORDER BY 1;"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1d),\n  COUNT(id) AS \"cEDH\"\nFROM games\nWHERE $__timeFilter(created_at)\n  AND started_at is not null\n  AND games.guild_xid in(\n    113555415446413312, -- Competitive EDH\n    1225118416298315857, -- r/cEDH Discord\n    682734915846275184, -- Play to Win\n    530219227924267008, -- PWP\n    954838268275470367, -- ka0s Tournaments\n    763138565231345665, -- WreckRoomCedh\n    1206898724266319882, -- Espanola cEDH\n    1036729704180355202, -- Training Grounds\n    799686008811290626, -- cEDH PT\n    1061492498402394132, -- cEDH Training Grounds\n    966025312368463922, -- cEDH DE\n    629303378685460530, -- AUS cEDH\n    1110129065152745505, -- UK cEDH\n    749653914839679057, -- cEDH Quebec\n    947983400483033148 -- PDX cEDH\n  )\nGROUP BY 1\nORDER BY 1;"
    }
   ]
  }
 ]
}